name: Transvison UI CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'
    - name: Install Dependencies
      run: npm install
    - run: "echo starting to build"
    - run: docker build -t transvision-ui .
   # - run: echo ${{ secrets.DOCKER_HUB_USERNAME }}  ${{ secrets.DOCKER_HUB_PASSWORD }}
   # - run: docker login --username ${{ secrets.DOCKER_HUB_USERNAME }} --password ${{ secrets.DOCKER_HUB_PASSWORD }}
   # - run: docker tag transvision/transvision-ui:1.0.0.${{env.build_no}}
   # - run: docker push transvision/transvision-ui:1.0.0.${{env.build_no}}
      